Fixed issue with false positives of `0` & `1` boolean values
singer-io/tap-workday-raas pull request #10
Opened 2022-07-15 07:31 UTC by Vi6hal

transform

# Description of change
Modified the `_transform` method of the Transformer class.

# Manual QA steps
 - 
 
# Risks
 - 
 
# Rollback steps
 - revert this branch

co-author @rdeshmukh15

2022-07-15 08:08 UTC, dbshah1212 commented on tap_workday_raas/discover.py
> +                "metadata": stream_md,
Comma at the end of dict not required.

2022-07-15 08:08 UTC, dbshah1212 commented on tap_workday_raas/discover.py
> +                                                   replication_method="FULL_TABLE",)
Comma at the end of dict not required.

2022-07-15 08:08 UTC, dbshah1212 commented on tap_workday_raas/discover.py
> +                               "items": complex_type_mapping[elem_type],}
Comma at the end of dict not required.

2022-07-15 08:17 UTC, dbshah1212 commented on tap_workday_raas/transform.py
> +            if isinstance(data, str) and (data.lower() == "false" or data.lower() == "0"):
```suggestion
            if isinstance(data, str) and (data.lower() in ("false","0")):
```

2022-07-15 08:51 UTC, rdeshmukh15 commented on tap_workday_raas/discover.py
> +                "metadata": stream_md,
done

2022-07-15 08:51 UTC, rdeshmukh15 commented on tap_workday_raas/discover.py
> +                                                   replication_method="FULL_TABLE",)
done

2022-07-15 08:55 UTC, rdeshmukh15 commented on tap_workday_raas/discover.py
> +                               "items": complex_type_mapping[elem_type],}
done

2022-07-15 08:58 UTC, rdeshmukh15 commented on tap_workday_raas/transform.py
> +            if isinstance(data, str) and (data.lower() == "false" or data.lower() == "0"):
done

2022-07-15 09:29 UTC, dbshah1212 approved these changes

2022-07-19 05:27 UTC, dbshah1212 approved these changes

2022-07-19 05:49 UTC, savan-chovatiya requested changes
Can you please add a unit test cases for different scenarios of boolean values?

2022-07-19 09:24 UTC, savan-chovatiya approved these changes

2022-07-20 14:39 UTC, merged